plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}

obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 1.0
#footprint: [[0.24,0.35],[0.24,-0.35],[-0.24,-0.35],[-0.62,-0.15],[-0.62,0.15],[-0.24,0.35]]
robot_radius: 0.35
inflation_radius: 0.5

observation_sources: head_cloud

head_cloud: {
            sensor_frame: head_camera, 
            data_type: PointCloud2, 
            topic: /walker/camera/headPointCloud, 
            marking: true, 
            clearing: false
            }
