controller_list:
  - name: fake_walker_head_controller
    joints:
      - head_j1
      - head_j2
  - name: fake_walker_left_arm_controller
    joints:
      - left_limb_j1
      - left_limb_j2
      - left_limb_j3
      - left_limb_j4
      - left_limb_j5
      - left_limb_j6
      - left_limb_j7
  - name: fake_walker_right_arm_controller
    joints:
      - right_limb_j1
      - right_limb_j2
      - right_limb_j3
      - right_limb_j4
      - right_limb_j5
      - right_limb_j6
      - right_limb_j7
  - name: fake_walker_left_hand_controller
    joints:
      - left_index_j1
      - left_index_j2
      - left_middle_j1
      - left_middle_j2
      - left_pinky_j1
      - left_pinky_j2
      - left_ring_j1
      - left_ring_j2
      - left_thumb_j1
      - left_thumb_j2
  - name: fake_walker_right_hand_controller
    joints:
      - right_index_j1
      - right_index_j2
      - right_middle_j1
      - right_middle_j2
      - right_pinky_j1
      - right_pinky_j2
      - right_ring_j1
      - right_ring_j2
      - right_thumb_j1
      - right_thumb_j2
  - name: fake_walker_left_leg_controller
    joints:
      - left_leg_j1
      - left_leg_j2
      - left_leg_j3
      - left_leg_j4
      - left_leg_j5
      - left_leg_j6
  - name: fake_walker_right_leg_controller
    joints:
      - right_leg_j1
      - right_leg_j2
      - right_leg_j3
      - right_leg_j4
      - right_leg_j5
      - right_leg_j6
initial:  # Define initial robot poses.
  - group: walker_head
    pose: home
  - group: walker_left_arm
    pose: home
  - group: walker_right_arm
    pose: home
  - group: walker_left_hand
    pose: home
  - group: walker_right_hand
    pose: home
  - group: walker_left_leg
    pose: home
  - group: walker_right_leg
    pose: home